#ifndef ACCESSPOINTMANAGER_GLOBAL_H
#define ACCESSPOINTMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XQACCESSPOINTMANAGER_LIBRARY)
#  define XQACCESSPOINTMANAGER_EXPORT Q_DECL_EXPORT
#else
#  if defined(XQACCESSPOINTMANAGER_NO_LIBRARY)
#    define XQACCESSPOINTMANAGER_EXPORT
#  else
#    define XQACCESSPOINTMANAGER_EXPORT Q_DECL_IMPORT
#  endif
#endif

#endif // ACCESSPOINTMANAGER_GLOBAL_H
